/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class SomeTest2 {
    @Test
    public void test_demo_1() {
        Assert.assertTrue(true, "Test pass");
    }

    @Test(dependsOnMethods = {"test_demo_1"})
    public void test_demo_2() {
        Assert.assertTrue(false, "Test fail");
    }
}
