/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.Assert;
import org.testng.annotations.*;

public class SomeTest {

    private int count;

    private static final Logger log = LoggerFactory.getLogger(SomeTest.class);

    @Factory(dataProvider = "testDataProvider", dataProviderClass = DemoDataProvider.class)
    public SomeTest(int count){
        this.count = count;
    }

    @BeforeClass
    public void beforeClass() {
    }

    @BeforeMethod
    public void beforeMethod() {
        //throw new ClassCastException("exception");
    }

    @Test
    public void test() {
        Assert.assertTrue(count>0, "Test pass");
    }

    @Test()
    public void test_demo() {
        log.info("count: {}", count);
        Assert.assertFalse(count > 10, "Test fail when count is bigger than 10");
    }

}
